### ISSUE TITLE
Move VERSION into sourcecode

### ISSUE THREAD

**Issue by terrorobe** [pgmasters/backrest#109]
``ExtUtils::MakeMaker`` needs a version string to be able to build a makefile.

Currently this can be either hardcoded in the makefile or read from Perl code. If we were to move the version string to perl code we could keep the things that need to be touched on version bump to a minimum

See ``VERSION_FROM`` in http://perldoc.perl.org/ExtUtils/MakeMaker.html#Using-Attributes-and-Parameters; real world example from SpamAssassin:

https://github.com/apache/spamassassin/blob/08067d3f9848466246230d698005f4db4e44c2d2/Makefile.PL#L127
https://github.com/apache/spamassassin/blob/08067d3f9848466246230d698005f4db4e44c2d2/lib/Mail/SpamAssassin.pm#L97

**Comment by dwsteele** [comment]
Sounds reasonable.  I'm sure the current way is not very workable for a packaging perspective anyway.

**Comment by dwsteele** [comment]
Implemented in f210fe9.  Took a bit of doing to make Perl 5.10.1 happy with it.
Let me know how it looks.
