### ISSUE TITLE
'db-version' is required but not defined

### ISSUE THREAD

**Issue by eradman** [pgmasters/backrest#110]
Running from commit 61dfec, this is my command line:

    $ sudo -u postgres bin/pg_backrest backup --stanza=db --type=full \
        --db-path=/pg_data2/9.4 --cmd-psql=/usr/pgsql-9.4/bin/psql

When I run this it seems to create a full backup, then exits with these messages:

    2015-06-22 08:10:16.174 T00   WARN: aborted backup of same type exists, will be cleaned to remove invalid files and resumed
    2015-06-22 08:10:59.523 T00 ASSERT: manifest section 'db', value 'db-version' is required but not defined
    2015-06-22 08:10:59.527 T00  ERROR: process terminated on signal or exception, 0 threads stopped
    manifest section 'db', value 'db-version' is required but not defined at bin/../lib/BackRest/Ini.pm line 403
            BackRest::Ini::get('BackRest::ArchiveInfo=HASH(0x2aea990)', 'db', 'db-version') called at bin/../lib/BackRest/ArchiveInfo.pm line 145
            BackRest::ArchiveInfo::archiveId('BackRest::ArchiveInfo=HASH(0x2aea990)') called at bin/../lib/BackRest/Archive.pm line 338
            BackRest::Archive::getCheck('BackRest::Archive=HASH(0x2aee978)', 'BackRest::File=HASH(0x245de88)') called at bin/../lib/BackRest/Backup.pm line 736
            BackRest::Backup::backup('/pg_data2/9.4', 0) called at bin/pg_backrest line 284
            eval {...} called at bin/pg_backrest line 130
     at bin/pg_backrest line 13
            main::__ANON__('manifest section \'db\', value \'db-version\' is required but...') called at /usr/share/perl5/Carp.pm line 45
            Carp::confess('manifest section \'db\', value \'db-version\' is required but...') called at bin/../lib/BackRest/Ini.pm line 403
            BackRest::Ini::get('BackRest::ArchiveInfo=HASH(0x2aea990)', 'db', 'db-version') called at bin/../lib/BackRest/ArchiveInfo.pm line 145
            BackRest::ArchiveInfo::archiveId('BackRest::ArchiveInfo=HASH(0x2aea990)') called at bin/../lib/BackRest/Archive.pm line 338
            BackRest::Archive::getCheck('BackRest::Archive=HASH(0x2aee978)', 'BackRest::File=HASH(0x245de88)') called at bin/../lib/BackRest/Backup.pm line 736
            BackRest::Backup::backup('/pg_data2/9.4', 0) called at bin/pg_backrest line 284
            eval {...} called at bin/pg_backrest line 130
     at bin/pg_backrest line 336
     at bin/pg_backrest line 13
            main::__ANON__('manifest section \'db\', value \'db-version\' is required but...') called at /usr/share/perl5/Carp.pm line 45
            Carp::confess('manifest section \'db\', value \'db-version\' is required but...') called at bin/pg_backrest line 336

Is there an error in my command line? I did not create `/etc/pg_backrest.conf`.

**Comment by dwsteele** [comment]
It looks like you are resuming an aborted backup?  Try --no-resume and see if that works.

**Comment by dwsteele** [comment]
Actually, it looks like you did not set an archive_command on your db.  If you want to backup without archive you'll need to use --no-archive-check.
And I need to improve that error message.

**Comment by eradman** [comment]
Right you are; I didn't set the archive command

    archive_command = 'bin/pg_backrest --stanza=db archive-push %p --db-path=/pg_data2/9.4'

Looks like I have a good backup now! Will keep testing

**Comment by dwsteele** [comment]
Cool - and I'm working right now on making that error better.

**Comment by dwsteele** [comment]
Improved the error message in 3f841fc.  It now looks like:
```
ERROR: [130]: archive.info does not exist but is required to get WAL segments
              HINT: Is archive_command configured in postgresql.conf?
              HINT: Use --no-archive-check to disable archive checks during backup if you have an alternate archiving scheme.
```
