### ISSUE TITLE
Take postgres out of backup mode when pg_backrest is terminated

### ISSUE THREAD

**Issue by eradman** [pgmasters/backrest#153]
If the backup is interrupted it can leave the database in backup mode:

    $ sudo -u postgres bin/pg_backrest  -stanza=demo backup --db-path=/pg_data2/9.4
    2015-11-11 15:12:21.615 T00   WARN: no prior backup exists, incr backup has been changed to full
    2015-11-11 15:12:30.104 T00  ERROR: [138]: process terminated on a INT signal

    $ sudo -u postgres psql
    postgres=# select pg_stop_backup();
    NOTICE:  pg_stop_backup complete, all required WAL segments have been archived
     pg_stop_backup 
    ----------------
     0/2D000128
    (1 row)

Can `pg_backrest` handle this automatically if it is rudely inturrupted with `SIGINT` or `SIGTERM`?

**Comment by dwsteele** [comment]
I prefer not to attempt a pg_stop_backup() when an error occurs for a variety of reasons, mostly related to exiting in a timely fashion and not masking the original error.  Also, it wouldn't work for a kill -9, power event, etc.

Instead, I have added the stop-auto option to deal with this situation: http://www.pgbackrest.org/user-guide.html#backup-option-stop-auto

Check it out and let me know what you think.

**Comment by eradman** [comment]
The `stop-auto` is what I was looking for--I tested it and it works.
