### ISSUE TITLE
duplicated log section entries in config file

### ISSUE THREAD

**Issue by adunstan** [pgmasters/backrest#159]
[andrew@ad-f22 backrest-release-0.88]$ perl -cw bin/pg_backrest 
Constant subroutine BackRest::Config::Config::OPTION_LOG_LEVEL_CONSOLE redefined at /usr/share/perl5/vendor_perl/constant.pm line 156.
Constant subroutine BackRest::Config::Config::OPTION_LOG_LEVEL_FILE redefined at /usr/share/perl5/vendor_perl/constant.pm line 156.
bin/pg_backrest syntax OK
[andrew@ad-f22 backrest-release-0.88]$ 
[andrew@ad-f22 backrest-release-0.88]$ grep -rn use.*OPTION_LOG_LEVEL .
./lib/BackRest/Config/Config.pm:279:use constant OPTION_LOG_LEVEL_CONSOLE                               => 'log-level-console';
./lib/BackRest/Config/Config.pm:281:use constant OPTION_LOG_LEVEL_FILE                                  => 'log-level-file';
./lib/BackRest/Config/Config.pm:424:use constant OPTION_LOG_LEVEL_CONSOLE                               => 'log-level-console';
./lib/BackRest/Config/Config.pm:426:use constant OPTION_LOG_LEVEL_FILE                                  => 'log-level-file';
[andrew@ad-f22 backrest-release-0.88]$ perl -cw ~/perl5/bin/pg_backrest

**Comment by dwsteele** [comment]
Fixed in fe9c665.  I don't think this is worth cutting a release for but let me know if you think differently.  I'm surprised this was not caught by `use warnings FATAL => qw(all);`.

**Comment by adunstan** [comment]
I don't thing it's worth a new release either. It was just annoying. Pretty much the first thing I ever do with a perl program from elsewhere is run it with -cw. It's worth running as part of your normal test regime.

**Comment by dwsteele** [comment]
A regression test has been added.  Thanks for the report.
