### ISSUE TITLE
Info command

### ISSUE THREAD

**Issue by dwsteele** [pgmasters/backrest#26]
Some kind of info command to see when the last backup was done for each, this can be done by stanza or globally.
It would be nice to see:
1) Last backup
2) Number of backups of each type and date
3) What backups are currently running
4) Failed backups in temp

The internal format for this should be JSON so it can easily for formatted into text, Nagios alerts - whatever.

**Comment by terrorobe** [comment]
+1 for having a machine-parseable output for automated checks.

Might also make sense to see what [barman](http://docs.pgbarman.org/#available_commands) has implemented

**Comment by dwsteele** [comment]
JSON output will be an option - something like this:

{
   "db" : {
      "backup-list" : [
         {
            "archive-start" : [ARCHIVE-START],
            "archive-stop" : [ARCHIVE-STOP],
            "format" : [FORMAT-1],
            "label" : "[BACKUP-FULL-1]",
            "timestamp-copy-start" : "[TIMESTAMP]",
            "timestamp-start" : "[TIMESTAMP]",
            "timestamp-stop" : "[TIMESTAMP]",
            "type" : "full",
            "version" : [VERSION-1]
         }
      ]
   }
}

**Comment by terrorobe** [comment]
A "status" field (ok? failed? running? resumable?) would be helpful too if this list will contain non-ok backups as well - not sure how they're handled at the moment.

**Comment by dwsteele** [comment]
There will be additional fields at the stanza level to give the user info on what is going on.  I'll be able to add more states to the status once time-based expiration is implemented.  I'm still working on the states that will be available but probably to start it will be: ok, error.  In case of an error, there be a boolean indicating if the backup can be resumed.  Another boolean will indicated if a backup is currently running.

**Comment by dwsteele** [comment]
Implemented in 148836f.  New issues will be created for follow-on work.
