### ISSUE TITLE
Add checksum-delta option

### ISSUE THREAD

**Issue by dwsteele** [pgmasters/backrest#28]
Checksums are calculated during the backup process, but the delta is still done during diff/incr backups.
Add a new option checksum_delta (default n) that does the delta using checksums.  Of course, if the timestamp or size has changed the checksum does not need to be calculated.

**Comment by dwsteele** [comment]
Moved to xml backlog.

**Comment by cmwshang** [comment]
Committed: https://github.com/pgbackrest/pgbackrest/commit/904550c97f674d3f576d3113756f2b5c89b55ddf
