### ISSUE TITLE
Abandon threads and go to processes

### ISSUE THREAD

**Issue by dwsteele** [pgmasters/backrest#48]
Even with the thread refactor they are not reliable on all platforms.  It's time to move to processes.  Performance testing has also show that they are not very efficient.

Before starting:
1) Run four processes from the command line in parallel and make sure this is actually faster and make sure this is faster than running four threads.  RESULTS: Processes are not measurably faster than threads, but it's still a good idea to replace them for portability reasons.  Threads are not well supported and in fact are officially deprecated.

There will be a few steps to this effort:
1) Separate protocol from remote
2) Create local module
3) Create a ProcessGroup module to manage local helpers
4) Replace ThreadGroup with process group

**Comment by dwsteele** [comment]
Tried running four separate processes and was only somewhat successful with queuing and signalling this small difference would likely melt away.  Probably limitations of my laptop and/or Perl.  Will need to test on bigger hardware to be sure.
# 1 thread 32.5s
# 4 threads 15.4s
# 4 processes 12s

**Comment by direvus** [comment]
Just chiming in here.  The use of Perl ithreads is also a significant barrier to entry on Gentoo.  The perl package on Gentoo is built without ithreads by default -- the packagers seem to take the view that the compatibility risks of ithreads generally outweigh its usefulness.

I don't personally have an opinion about ithreads, but it does mean that if you want to install pgbackrest on Gentoo, you must first rebuild perl with non-default options, and then rebuild everything that is linked against perl.  It's not ideal.

All of this being a rather long-winded way of saying "+1 to ditching ithreads and going to processes".

**Comment by dwsteele** [comment]
It may not look like it from the comments but I've already decided to go this way.  Even though I have threads working OK on the platforms that support them there are issues other than portability.  It happens that I have a decent protocol layer for communicating with the remotes so no reason that can't be applied locally.  Except for time, of course.  Was hoping to have it done before the Ottawa conference but now that's looking unlikely.  It's a top priority, though.

**Comment by direvus** [comment]
Cool, thanks for the reply @dwsteele.  I am very interested in seeing a subprocess-based pgbackrest, so if there is any way that I can assist, let me know.

**Comment by dwsteele** [comment]
I appreciate that - the biggest help would be to test out the code once I have something working.  I plan to start on that in the next week once I'm done with the current info functions so I'll let you know.

**Comment by dwsteele** [comment]
Moved to xml backlog.

**Comment by David-Gould** [comment]
If you would like some testing on high core count hardware, I can do that.

**Comment by dwsteele** [comment]
If you would be willing to test dev versions that would be awesome.  I'll let you know when I have something.

**Comment by David-Gould** [comment]
I'd be happy to test dev versions.

**Comment by dwsteele** [comment]
@direvus Perl threads were replaced with child processes in 1.07, if you are still interested.

**Comment by direvus** [comment]
That's great, thanks @dwsteele.  I look forward to taking it for a spin.
