### ISSUE TITLE
Time-based retention

### ISSUE THREAD

**Issue by dwsteele** [pgmasters/backrest#54]
Create a setting that allows a time period to be set for retention.  Right now only a certain number of backups can be set.  If retention-full=2 and two backups are done back to back, then the time period of protection will be very short.

The new option retention-period will be expressed in hours, days, weeks, months, years and will work with current retention like this:  The time period will be honored but middle backups will be pruned to match retention-full.  For example, if retention-period=2 weeks full-rentention=2 and a third full backup was taken, the first one would be pruned if it were older than two weeks, else the middle one will be pruned.  This gives two weeks of backup coverage but keeps the number of backups down.

As part of this feature, WAL should be expired as part of retention-period if nothing else is set.  This will support installations that are using backrest only for archiving.

**Comment by terrorobe** [comment]
For WAL-expiration I'd suggest having these expiration modes:

* keep all WAL (no expiry)
* keep WAL referenced by existing backups (new default?)
* keep WAL for last $n hours _plus_ WAL needed for restore purposes
* keep only WAL segments needed for restore purposes

**Comment by terrorobe** [comment]
This should also address the open bug that it's possible to have unrestorable backups when running with archive-copy=n and have a mismatch between retention-archive and retetion-full/diff.

**Comment by dwsteele** [comment]
Improve expiration to keep enough WAL to make backups consistent even if the WAL is outside of the retention period.  Even better would be to only do this for backups where archive copy = n.  This param should be added to the manifest.

**Comment by dwsteele** [comment]
Issue #93 has been opened to deal with the WAL expiration / archive copy issue.

**Comment by dwsteele** [comment]
Moved to xml backlog.

**Comment by sujiplr** [comment]
@dwsteele , is this feature got added in some other way ? or adding this time based retention is not going to be considered? Can you please help. 

In our environment, backup retention is based on days. Can you help, how can I implement that using pgbackrest ?
