### ISSUE TITLE
Write stanza name into archive.info and check it

### ISSUE THREAD

**Issue by dwsteele** [pgmasters/backrest#59]
This will guard against dirs being renamed and is good info to have.

**Comment by dwsteele** [comment]
This is probably not that useful since the db system IDs can be matched up and would make renaming more complicated.

**Comment by terrorobe** [comment]
I think there would be some merit to write "superfluous" information, like

* host
* port
* stanza name

et al

to the manifest. Even when not used by backrest itself it helps being sure where the backup came from.

As for the system-id I think this needs documenting on how to extract it on your own from a running postgres instance.

**Comment by dwsteele** [comment]
Fair enough - this information could be written into the backup.info file.  I'm trying the keep backup.manifest lean and mean.

**Comment by dwsteele** [comment]
Moved to xml backlog.
