### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by terrorobe** [pgmasters/backrest#69]
This is just a collection of documentation improvements, if you want I can do them to the best of my knowledge.

* better local/remote backup tutorials
* s/archive-retention/retention-archive/
* document default values for all configuration variables (e.g. unset)
* Provide an index for the README.md
  * Maybe even add hr's to sections to improve readability
* move changelog to separate file

More thorough explanation:

It would make sense to talk more in detail about these things:

* How does backrest differ from barman?
  * focus of development
  * functional differences
  * no need to brag/accuse, see e.g. https://consul.io/intro/vs/zookeeper.html
* How does the interaction between pg_backrest and the remote look like?
  * Should answer how the data is backed up from postgres server to backrest and restored from backrest to postgres

**Comment by dwsteele** [comment]
Anything you'd like to contribute here would be appreciated.  As I'm sure you know it can be hard for a developer to get into the user mindset!

**Comment by dwsteele** [comment]
Change log was split out in 61c729b.

**Comment by terrorobe** [comment]
\o/ for the record/passersby: 2edf5d4bf7b47b4fd3fd446740a82c35be84dbda ! ;)

**Comment by dwsteele** [comment]
I think most of this is covered in the user guide: http://www.pgbackrest.org/user-guide.html

A what makes backrest different than other backup software is still a good idea but has been added to the xml backlog for now.
