### ISSUE TITLE
New configuration setting "repository owner"

### ISSUE THREAD

**Issue by terrorobe** [pgmasters/backrest#73]
e.g. repo-owner. This should even be mandatory.

backrest should either abort or try setuid to the defined user to prevent permission issues down the road.

Currently backrest will fail with an overly verbose error message when log- & lock-files or directories are not writeable by the current user.

e.g.

```
$ /opt/backrest/bin/pg_backrest.pl backup --stanza=slave --type=full
2015-05-19 10:48:30.478 T00  ERROR: unable to open lock file /srv/pgbackups/lock/slave-backup.lock
2015-05-19 10:48:30.479 T00  ERROR: process terminated on signal or exception, 0 threads stopped
unable to open lock file /srv/pgbackups/lock/slave-backup.lock at /opt/backrest/bin/../lib/BackRest/Lock.pm line 82.
	BackRest::Lock::lockAcquire('backup') called at /opt/backrest/bin/pg_backrest.pl line 131
	eval {...} called at /opt/backrest/bin/pg_backrest.pl line 107
 at /opt/backrest/bin/pg_backrest.pl line 285.
```

**Comment by dwsteele** [comment]
Yes, that's pretty ugly so I've marked it as a bug.  I'd still prefer to keep it optional, but also clean up the error message.

**Comment by dwsteele** [comment]
Moved to xml backlog.
