### ISSUE TITLE
Support "include"-directories for config snippets

### ISSUE THREAD

**Issue by terrorobe** [pgmasters/backrest#75]
It would be very helpful if backrest would support a "pg_backrest.conf.d"-style config include directory, e.g. when auto-generating stanzas with a config management system.

**Comment by dwsteele** [comment]
I think it would be best to consider #87 before this.  It's not clear to me how config files would best be split.  By stanza?  What about operation settings - would they all go in pg_backrest.conf?

**Comment by terrorobe** [comment]
I guess what most daemons these days do is concatenate all the included files in glob-order and then throw the combined file against the config parser - the user is responsible that the stuff that gets fed to the daemon is semantically correct.

I render the configs as follows: 

* for the client:
  * global parameters
  * a snippet containing configuration parameters from the server
  * a snippet containing the stanza 
* for the server:
  * global parameters
  * for each client a snippet containing the stanza

Especially on the server it would be nice if each client stanza could be offloaded into a separate file.

See http://www.postgresql.org/docs/current/static/config-setting.html#CONFIG-INCLUDES for examples from Postgres itself.

In my opinion it'd suffice to support an "include_dir" equivalent.

**Comment by dwsteele** [comment]
OK, I see.  Let me think about that.  Not very likely for the Ottawa release since I can do it without breaking anything.

What do you think about the location of pg_backrest.conf in /etc (by default)?  Would you put it in a subdir?

**Comment by terrorobe** [comment]
I think the current approach is that if you expect to have more than one file on a regular basis you create a subdirectory in /etc - so without include_dir support I don't see the need.

And there's software like rsyslogd which comes with a /etc/rsyslog.conf and a /etc/rsyslog.d/ directory ;) 

I'm going to have a chat with Debian developers for #78 - I'll let you know what they recommend for backrest!

**Comment by dwsteele** [comment]
Excellent, thanks!

**Comment by dwsteele** [comment]
Moved to xml backlog.
