### ISSUE TITLE
provide backup-scheduling mechanism

### ISSUE THREAD

**Issue by terrorobe** [pgmasters/backrest#77]
It would be great if you could specify target backup intervals for each stanza and backup-level and have backrest execute backups automatically - either via periodic cron invocations (noop'ing if nothing is to be done) or as a daemon

**Comment by dwsteele** [comment]
I like this idea but it's not at the top of the list.  Cron works fine in current installations and there are higher priority items to think about.  Marking this as backlog for now.

**Comment by dwsteele** [comment]
Honestly I just don't see backrest getting into this business at all.  If it does, it will be far in the future.
