### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by terrorobe** [pgmasters/backrest#78]
On Debian & Ubuntu backrest depends only on already-packaged Perl modules, so it'd be trivial to package and ship it via apt.postgresql.org.

If you want I can go ahead and work on this.

**Comment by dwsteele** [comment]
Sure, that would be great.  I'm planning the next major release right before PGCon on June 16th.  It would be awesome if there was a packed version.

**Comment by terrorobe** [comment]
No call to action, more personal notes since I didn't get around working on it this week and the notes are rotting in my scratchpad:

We're going to need a perl-style Makefile to make use of the perl debhelper. I'll try to continue this weekend.

Relevant links:

* https://www.debian.org/doc/manuals/maint-guide/dreq.en.html
* https://www.debian.org/doc/debian-policy/ch-relationships.html

* https://sources.debian.net/src/barman/1.4.1-1/debian/
* https://sources.debian.net/src/mytop/1.9.1-2/debian/rules/
* https://www.debian.org/doc/packaging-manuals/perl-policy/ch-perl.html

**Comment by dwsteele** [comment]
I'm still planning to do the binary rename (pg_backrest.pl -> pg_backrest) for the Ottawa release.

**Comment by dwsteele** [comment]
Closed for now -- not sure if I want to be in the business of packaging.
