### ISSUE TITLE
wishlist: reduce configuration settings necessary for multi-host setups

### ISSUE THREAD

**Issue by terrorobe** [pgmasters/backrest#85]
It would be great if we could have backrest discover some of the configuration settings from the remote node to reduce the amount of configuration that needs to be kept in sync across nodes.

on backup server:
* db-path

on db server:
* repo-remote-path

**Comment by dwsteele** [comment]
Agreed - I've been thinking about something like this for a while.

**Comment by dwsteele** [comment]
Will be addressed as part of issue #164.
