### ISSUE TITLE
Provide a configuration example which combines backups from local and remote databases

### ISSUE THREAD

**Issue by terrorobe** [pgmasters/backrest#86]
With the current configuration layout it's not trivial/straightforward to do a configuration where you have

* a backrest user which is different from the postgres user
* a backup server which does backups from local & remote postgres databases

Since this is probably not a too uncommon, provide a sample configuration.

It should boil down to 

* having different "repositories" for archive spooling (owned by postgres) and the actual backups (owned by backrest)
* overriding the global repo-path in the client stanza to point to the archive spool directory

Communication/permission switching between local postgres and backrest should be done via SSH for now in lieu of having proper UID handling in place. 

I'm not a big fan of the current approach to have context-dependant behaviour of what the "repository" is used for, I think the UX would improve if there were discrete "spool" and "repository" directories, where "clients" only need a spool directory and the backup-server only needs a repository directory.

**Comment by dwsteele** [comment]
I'm not so sure that sounds like a typical install, but it would certainly be a good example of how complex installs can be managed.

I thought about discrete spool and repo paths, but they would still require lock and log paths so in the end it seemed best to combine them.  A repo just holds whatever you need to store locally, be it spool or backups.  That why the term repo instead of archive or backup whatever.  Does that make sense and do you think it could be clarified in the docs?

Or do you think the idea is just broken?

**Comment by terrorobe** [comment]
You're right, from a programmatic approach it makes sense to keep the archive spool and backup repositories very close.

From an ops perspective things look different - it took a high cognitive load to differentiate between the uses of the repositories, especially when building configuration management for backrest. [1] 

And the case I outlined above shows the limit where the similarity breaks down:

* log-shipping databases need a directory for archive spooling, logs and locks.
* backup servers need a directory for keeping backups, archive storage, logs and locks.

I'm sure that you could extend the documentation to better highlight these differences but the configuration will still feel cumbersome.

Having discrete configuration variables for a "backup-repo" and "spool-repo" [2] would allow for a much cleaner configuration and less cognitive load when learning & using backrest.

[1] Not sure how familiar you're with puppet - for settings that need to be deployed on multiple servers you render configuration snippets for the local and the remote node and vice versa.

[2]  the latter could even default to the former as to not increase config verbosity

**Comment by dwsteele** [comment]
Or "spool-path" and "repo-path"?  In that case I could pull this off without any breakage in current installations.

**Comment by terrorobe** [comment]
I think I like the approach, +1 for keeping repo-path as is, not sure about "spool-path" as a name yet but it'll work.

One thought that came up was that if we were to allow repo-path to contain scp-like target definitions we could do minimum viable configs like this:

client w/ remote backrest repo:

(spool-path being mandatory when repo-path points to a remote repository)

```
[global:general]
spool-path=/srv/backrest-spool
repo-path=backrest@backup.example.com:/srv/backrest-repo

[global:archive]
archive-async=y

[main]
db-path=/data/db
```


client w/ local backrest repo:

```
[global:general]
repo-path=/srv/backrest-repo

[main]
db-path=/data/db
```

**Comment by dwsteele** [comment]
Naming things is always tough - especially when you can't change your mind later without annoying legions of users.

I like the compact scp-ish syntax.  Wouldn't be too hard to implement, I think.  Probably more useful on the command line but looks good in conf as well.

**Comment by terrorobe** [comment]
Full ack WRT naming & annoying users - I guess that's where http://semver.org/ can be handy.

**Comment by dwsteele** [comment]
These config examples are given in the user guide.  Spool-path option will be introduced in 1.0.
