### ISSUE TITLE
Get rid of configuration sections

### ISSUE THREAD

**Issue by terrorobe** [pgmasters/backrest#87]
Since the option-namespace is flat anyhow (everything is allowed on the command line) there's no benefit of having separate sections for different parameters in the config file.

At the moment it only adds unnecessary verbosity to configuration files and complicates automated rendering via configuration management tools.

**Comment by dwsteele** [comment]
Not everything is completely flat.  Can have multiple layers in general, global, and stanzas.  For instance, compress=n can be set in general, then set to n for the backup operation and to n in a particular stanza.  There are installed cases that use this kind of logic.

On the command line everything is flat because the stanza and operation is fixed.  I agree that a lot of the sections could be removed, but there would still need to be three levels to duplicate current functionality: general, operation, stanza.  That really only eliminates the log and command sections.

Ideas?

**Comment by terrorobe** [comment]
Hm, compress is only documented for "general" so I wouldn't expect it to work in other sections. 

Do you use operation-specific settings at the moment which you couldn't easily move to either global or into a stanza?

If there aren't too many my current gut-feeling would be that I'd: 

* drop the operation-specific sections, 
* run with [global] & [$stanza] sections in the config plus the command line options
* provide additional configuration parameters where operation-specific settings might be necessary

**Comment by dwsteele** [comment]
OK, good point - it's always something with the docs, isn't it?.

There is one very large installation (36 stanzas) where compress is different for backup and archive.  It's a fairly useful case actually.  Even if you were willing to configure that per-stanza (painful) it's not clear to me how that would would with "flat" configuration.  Would it be "backup-compress=n" and "archive-compress=y"?

**Comment by terrorobe** [comment]
Don't beat yourself up over docs - it's always hard to put yourself in the shoes of a user when you've written the software yourself :)

Ahh, that makes sense! Yeah, if it's the only option you can think of, having discrete configuration values would be a good move.

Eventually it would tremendously reduce the complexity of a "feature-complete" configuration renderer since you don't need a mapping which setting belongs to which sections and most likely prevent quite a few user mishaps as well.

**Comment by dwsteele** [comment]
On the other hand if you are automating you can write everything into the stanza sections and skip general and operation sections altogether.  That leaves inheritance for the people who are slogging along manually.

**Comment by terrorobe** [comment]
But I still would need the section-qualifier in the stanza, e.g. "[main:command]" as shown in https://github.com/pgmasters/backrest/blob/master/README.md#simple-single-host-configuration ?

**Comment by dwsteele** [comment]
Yes - that's the idea.  Is that really much worse than "command-option"?

**Comment by terrorobe** [comment]
Yeah, since you need to know in which section each config setting goes and need to emit stanza:section headers for each group of settings.

Much easier to just barf whatever the user wants into a single stanza and be done with it ;)

**Comment by dwsteele** [comment]
I hope 18fd25233b1db7b3197f5d8dc537d239dcfc7aba addresses most of your concerns.  You are still require to have a stanza section but all options can be put into that section of you desire.  global and the command sections are now completely optional.

**Comment by terrorobe** [comment]
That's a tremendous improvement, thank you very much! Unfortunately I don't have an environment where I use backrest at the moment, but I'll give it a spin as soon as there's databases that need backups again :)
