### ISSUE TITLE
Thoughts on repo & release management

### ISSUE THREAD

**Issue by terrorobe** [pgmasters/backrest#88]
I noticed two things that could cause surprises down the road:

* The VERSION in dev doesn't reflect that it's a dev branch. This might cause confusion for users running on a checkout and reporting errors. Adding a -dev suffix until release should be a good safety measure

* The master branch doesn't contain the commit history. This is a bit counterintuitive since informed users might want to check _how_ a specific issue has been fixed - picking through the complete release-diff isn't very helpful in this regard. The dev branch seems to contain the complete history but this isn't assured to the user.

**Comment by dwsteele** [comment]
Good call on the version.  I'll do something about that.

Backrest uses the gitflow model which maintains two histories: release and development.  This would be worth adding to the docs to make it clear, though.

**Comment by terrorobe** [comment]
Oh, didn't know about gitflow - thanks, makes sense! Adding a pointer to it would be helpful!

**Comment by dwsteele** [comment]
I thought about it and I don't think having a special dev version makes sense in the gitflow model.  The idea is that master always holds the last released version and that dev can be released at any time without modification.

Since master is also the default branch, nobody should get a dev version unless they checkout the dev branch.  In that case will a version number really stop them?

**Comment by dwsteele** [comment]
Repo & release management documented in 5fce709.

**Comment by terrorobe** [comment]
> Since master is also the default branch, nobody should get a dev version unless they checkout the dev branch. In that case will a version number really stop them?

Depends on your release cadence and how adventurous your users are ;)

I currently tail dev and reset the version number by hand as to not mislead any colleagues. In the end it's all about reducing confusion.

**Comment by dwsteele** [comment]
Sure, but it also increases the chances of introducing a dev version into master.  I may decide to renumber a release but there's generally no need.

My stance is that only power-users like you should even *consider* tailing dev and then they'll know what to do.  And I'm always happy to cut a release if there's need.  That's the benefit of having a stable dev branch.

Anyway - I'll keep thinking about it but for now leave as is.

**Comment by terrorobe** [comment]
:+1:
