### ISSUE TITLE
Move archive-max-mb archive-stop checks to end of archive-push?

### ISSUE THREAD

**Issue by terrorobe** [pgmasters/backrest#90]
Currently the workflow to clear archive-stop situations when archive-max-mb was exceeded looks something like this:

* Clear problem causing archive-push failures
* remove lock-file
* pg_switch_xlog()
  * causes archive-push
  * tests archive-max-mb, is still exceeded, creates lockfile
  * pushes all files in archive/$hostname/out
* remove lock-file

It would be great if the test could be moved to after the archive-push so to not have to remove the lock-file twice.

**Comment by dwsteele** [comment]
Moving it after is tricky because it increases the possibility of an error that would prevent the check from being done.  However, having to remove the lock file twice sucks.  Let me see what I can do WRT ordering.

**Comment by dwsteele** [comment]
Fixed in 13e4eec.
