### ISSUE TITLE
Prevent misconfigured retention-archive setting

### ISSUE THREAD

**Issue by terrorobe** [pgmasters/backrest#93]
In light of the upcoming ottawa release I'd recommend that we either

document in the ``retention-archive`` setting that a too low configured value will result in unrestorable backups unless ``archive-copy`` is enabled

or

add a sanity check on ``backup`` (or ``expire``?) that verifies that ``retention-archive[-type]`` >= ``retention-(full|diff)`` or  ``archive-copy`` is enabled, otherwise emit a WARN message - if that sanity check is even deterministically possible.

Ideally it shouldn't be possible for users to have required WAL files expired without their knowledge.

**Comment by dwsteele** [comment]
I'd like to fix this for Ottawa.  Stephen's suggestion was just to keep the WAL in the archive required to make the DBs consistent for any backups that don't have archive-copy turned on.  I think this is a good approach and it's not that hard to do.

**Comment by terrorobe** [comment]
:+1: on fixing it for good, wasn't sure how feasible it'd be with the current infrastructure
