### ISSUE TITLE
backup_stop needs a timeout

### ISSUE THREAD

**Issue by terrorobe** [pgmasters/backrest#94]
When doing a backup, after completing the data directory copy, backrest will:

* issue a ``pg_stop_backup()``
* wait for the corresponding WAL file to appear in the archive

The latter has a timeout of 600 seconds which is a good choice since it prevents "stuck" backups.

The former [can wait indefinitely](http://git.postgresql.org/gitweb/?p=postgresql.git;a=blob;f=src/backend/access/transam/xlog.c;h=666fa37e2a3f1d36a11d2311dc73930d016cf1ea;hb=d8179b001ae574da00c8f4549577095bf90f3337#l10529) if the ``archive_command`` causes errors.

It would be a good thing to either 

* have the same 600 second timeout for pg_stop_backup or 
* even err out immediately after encountering the wait message, since this indicates that there's an issue with the archive_command and we most likely won't get the stop point in finite time.

**Comment by dwsteele** [comment]
This is related (but not the same as) issue #25.  In fact, if pg_stop_backup() never returns, the backrest timer will never start.  If it were run asynchronously then the connection could be killed.

It's a problem, though - because if pg_stop_backup() does not return then the next backup with likely fail as well without some intervention.  I'm not completely sure what the solution is here.

**Comment by terrorobe** [comment]
> It's a problem, though - because if pg_stop_backup() does not return then the next backup with likely fail as well without some intervention. 

That's what stumped me as well for a bit but if you check do_pg_stop_backup in xlog.c  the CleanupBackupHistory() call is right above the wait and the only relevant thing happening after the wait is the return of the stoppoint. 

pg_stop_backup in xlogfuncs.c itself is just a thin wrapper around do_pg_stop_backup

I verified that by checking pg_is_in_backup() during the run, postgres is no longer in backup mode while backrest is waiting, so you don't leave the db in an unsafe state.

So in my opinion it's safe to just abort after issuing the pg_stop_backup() call and encountering the error message.

**Comment by dwsteele** [comment]
Right - that sounds correct and should be doable.  I've been planning to move the Db module over to DBI instead of exec'ing psql.  Any thoughts on that?

**Comment by dwsteele** [comment]
Implemented in e82afac.

Add db-timeout option for this feature.
