### ISSUE TITLE
"Corporate Identity"

### ISSUE THREAD

**Issue by terrorobe** [pgmasters/backrest#95]
Currently there's a few different ways that backrest is referred to:

 * backrest (e.g. Repository name)
 * PgBackRest (e.g. title in docs)
 * BackRest (e.g. Module name)
 * pg_backrest (e.g. executable files)

It would make sense to consolidate at least the user-facing parts to a common version to have some coherence.

**Comment by dwsteele** [comment]
Any preferences?

**Comment by terrorobe** [comment]
I'd prefer the minimalistic "backrest" though you'd have to add "database", "postgres" or "pg" on a vanilla google profile to find it. Same goes for "barman" though :)

**Comment by dwsteele** [comment]
Barman is the first hit when I google "barman", but pg_backrest is on page 5 when googling "backrest". :(

**Comment by dwsteele** [comment]
The theory was that the backrest model could be applied to other databases - thus the slightly schizo naming scheme.  Of course, PgBackRest is the only one implemented right now.

**Comment by terrorobe** [comment]
Nothing a bit of SEO can't fix ;)

Second favourite name would be pg_backrest which'd be in line with other postgres contrib software like pg_partman or pg_reorg.

**Comment by dwsteele** [comment]
Still can't decide on this so pushing to Dallas.

**Comment by dwsteele** [comment]
I think for the time-being at least I'm fine with the way the naming is done.

**Comment by dwsteele** [comment]
This has been done in 18fd25233b1db7b3197f5d8dc537d239dcfc7aba.  The project name and perl lib are pgBackRest, everything else is pgbackrest.  The repo will also be renamed before the 1.0 release.
