### ISSUE TITLE
executable names

### ISSUE THREAD

**Issue by terrorobe** [pgmasters/backrest#96]
On a somewhat related note to #95:

At least for Debian/Ubuntu packages we need to drop the .pl suffixes for the backrest binaries if we want to have them in PATH as per [Debian Policy](https://www.debian.org/doc/debian-policy/ch-files.html#s-scripts).

We can do this either during packaging (rewriting the default name for the backrest_remote if need be) or during a flag day release in master.

**Comment by dwsteele** [comment]
Would backrest/bin get added to the path or would pg_backrest.pl get added as a symlink in /usr/bin?

**Comment by terrorobe** [comment]
To my knowledge backrest (and maybe the backrest_remote as well [1]) would be placed in /usr/bin directly as files.

All modules go to /usr/lib/perl5 which is in Debian's @INC.

[1] could be that the remote needs to go somewhere else since it's not an user-facing component

**Comment by dwsteele** [comment]
I see - well, pg_backrest_remote.pl will be going away when I convert to processes.  There will be two new commands in pg_backrest.pl (local and remote) that will handle mufti-processing.

**Comment by terrorobe** [comment]
:+1: on nuking the remote, was wondering if it's functionality couldn't be implemented in the main binary with an "internal" command.

**Comment by dwsteele** [comment]
It also simplifies the protocol layer a bit so it's a win-win.  Still, that work is post-Ottawa so we may need to hold off on packaging a bit.  I'll keep this where it is for now and think about it.

**Comment by dwsteele** [comment]
Implemented in 57640d1.
